import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import Section from '../../components/UI/Section';
import Card from '../../components/UI/Card';
import Button from '../../components/UI/Button';
import SEO from '../../components/SEO';
const connectors = [
    'CSV / Excel', 'Jira', 'ServiceNow', 'Salesforce', 'HubSpot', 'Snowflake', 'PostgreSQL', 'Slack'
];
export default function Integrations() {
    return (_jsxs(_Fragment, { children: [_jsx(SEO, { title: "Integrations | Connect Your Data to SpaceConsole AI", description: "Connect Excel, CSV, Jira, Salesforce, and more. SpaceConsole AI unifies data from your existing toolstack." }), _jsxs(Section, { style: { paddingTop: '8rem', textAlign: 'center' }, children: [_jsx("h1", { style: { fontSize: '3rem', marginBottom: '1rem' }, children: "Connect your data, wherever it lives" }), _jsx("p", { style: { color: 'var(--color-text-secondary)', maxWidth: '600px', margin: '0 auto' }, children: "SpaceConsole AI unifies data from your existing toolstack into a single cohesive process view." })] }), _jsx(Section, { children: _jsx("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '2rem' }, children: connectors.map(name => (_jsx(Card, { className: "glass-panel", style: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '120px' }, children: _jsx("span", { style: { fontWeight: 'bold' }, children: name }) }, name))) }) }), _jsx(Section, { children: _jsxs("div", { style: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '4rem', alignItems: 'center' }, children: [_jsxs("div", { children: [_jsx("h2", { style: { fontSize: '2rem', marginBottom: '1rem' }, children: "Start Simple" }), _jsx("p", { style: { marginBottom: '1.5rem', lineHeight: 1.6 }, children: "Don't wait for IT to build an integration. Drag and drop a CSV or Excel export to get started instantly. Our AI maps the columns to process steps automatically." }), _jsx(Button, { to: "/book-demo", variant: "secondary", children: "Try with CSV" })] }), _jsxs("div", { children: [_jsx("h2", { style: { fontSize: '2rem', marginBottom: '1rem' }, children: "Enterprise Security" }), _jsx("p", { style: { marginBottom: '1.5rem', lineHeight: 1.6 }, children: "We take security seriously. All data is encrypted in transit (TLS) and at rest. Role-Based Access Control (RBAC) ensures only the right people see sensitive data." }), _jsxs("ul", { style: { paddingLeft: '1.2rem', color: 'var(--color-text-secondary)' }, children: [_jsx("li", { children: "Read-only access by default" }), _jsx("li", { children: "Encrypted in transit & at rest" }), _jsx("li", { children: "SOC2 Type II (Pending)" })] })] })] }) })] }));
}
