import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import styles from './Footer.module.css';
import Logo from '../Logo/Logo';
const currentYear = new Date().getFullYear();
function Footer() {
    return (_jsxs("footer", { className: styles.footer, children: [_jsxs("div", { className: styles.container, children: [_jsxs("div", { className: styles.brandColumn, children: [_jsx(Logo, {}), _jsx("p", { className: styles.tagline, children: "Turn your process into a live system: map it, measure it, fix it." }), _jsxs("div", { className: styles.socials, children: [_jsx("span", { className: styles.socialIcon, children: "Li" }), _jsx("span", { className: styles.socialIcon, children: "X" }), _jsx("span", { className: styles.socialIcon, children: "Gh" })] })] }), _jsxs("div", { className: styles.linksGrid, children: [_jsxs("div", { className: styles.column, children: [_jsx("h4", { children: "Product" }), _jsxs("ul", { children: [_jsx("li", { children: _jsx(Link, { to: "/product", children: "Overview" }) }), _jsx("li", { children: _jsx(Link, { to: "/pricing", children: "Pricing" }) }), _jsx("li", { children: _jsx(Link, { to: "/integrations", children: "Integrations" }) }), _jsx("li", { children: _jsx(Link, { to: "#", children: "Changelog" }) })] })] }), _jsxs("div", { className: styles.column, children: [_jsx("h4", { children: "Use Cases" }), _jsxs("ul", { children: [_jsx("li", { children: _jsx(Link, { to: "/use-cases/manufacturing", children: "Manufacturing" }) }), _jsx("li", { children: _jsx(Link, { to: "/use-cases/service-ops", children: "Service Ops" }) }), _jsx("li", { children: _jsx(Link, { to: "/use-cases/revops", children: "RevOps" }) }), _jsx("li", { children: _jsx(Link, { to: "/use-cases/marketing", children: "Marketing" }) })] })] }), _jsxs("div", { className: styles.column, children: [_jsx("h4", { children: "Resources" }), _jsxs("ul", { children: [_jsx("li", { children: _jsx(Link, { to: "/resources", children: "Blog" }) }), _jsx("li", { children: _jsx(Link, { to: "/resources", children: "Guides" }) }), _jsx("li", { children: _jsx(Link, { to: "/resources", children: "Help Center" }) }), _jsx("li", { children: _jsx(Link, { to: "/resources", children: "API Docs" }) })] })] }), _jsxs("div", { className: styles.column, children: [_jsx("h4", { children: "Company" }), _jsxs("ul", { children: [_jsx("li", { children: _jsx(Link, { to: "/company", children: "About" }) }), _jsx("li", { children: _jsx(Link, { to: "/company", children: "Contact" }) }), _jsx("li", { children: _jsx(Link, { to: "#", children: "Careers" }) }), _jsx("li", { children: _jsx(Link, { to: "/legal/privacy", children: "Privacy" }) }), _jsx("li", { children: _jsx(Link, { to: "/legal/terms", children: "Terms" }) })] })] })] })] }), _jsx("div", { className: styles.bottomBar, children: _jsxs("p", { children: ["\u00A9 ", currentYear, " Space Console AI. All rights reserved."] }) })] }));
}
export default Footer;
